import { useState, useCallback } from 'react';
import type { TripFormData, TripPlan, ReplanResult } from './types/trip.types';
import { Header } from './components/Layout/Header';
import { TripForm } from './components/Planner/TripForm';
import { ChatInterface } from './components/Replanner/ChatInterface';
import { ImportTrip } from './components/Replanner/ImportTrip';
import { ItineraryView } from './components/ItineraryView/ItineraryView';
import { useItinerary } from './hooks/useItinerary';
import { useChat } from './hooks/useChat';
import { useDisruption } from './hooks/useDisruption';
import { useGemini } from './hooks/useGemini';
import { buildPlanPrompt } from './utils/promptBuilder';
import { buildMapsSearchUrl } from './services/mapsService';
import { sanitizeInput } from './utils/sanitize';
import { FALLBACK_TRIP } from './services/fallbackData';
import { parseImportedTrip } from './services/importParser';

/**
 * Generates a readable text version of the trip plan for download.
 */
function generatePlanText(plan: TripPlan): string {
  const lines: string[] = [];
  lines.push(`🗺️ Wayshift Trip Plan — ${plan.destination}`);
  lines.push(`Budget: ₹${plan.totalBudgetINR.toLocaleString('en-IN')}`);
  if (plan.constraints.length > 0) {
    lines.push(`Constraints: ${plan.constraints.join(', ')}`);
  }
  lines.push('');
  lines.push('='.repeat(50));

  for (const day of plan.days) {
    lines.push('');
    lines.push(`📅 Day ${day.dayNumber} — ${day.date}`);
    lines.push('-'.repeat(40));
    for (const a of day.activities) {
      lines.push(`  ${a.time}  ${a.title}`);
      lines.push(`           📍 ${a.location}`);
      lines.push(`           ${a.description}`);
      lines.push(`           ⏱ ${a.durationMinutes} minutes`);
      if (a.mapsUrl) {
        lines.push(`           🔗 ${a.mapsUrl}`);
      }
      lines.push('');
    }
  }

  lines.push('='.repeat(50));
  lines.push('Generated by Wayshift — Plan once. Replan instantly.');
  return lines.join('\n');
}

/**
 * Main application component.
 * Full-width, light mode only, Google colors.
 */
export default function App() {
  const [mode, setMode] = useState<'planner' | 'replanner'>('planner');
  const [showFallbackBanner, setShowFallbackBanner] = useState(false);
  const [importLoading, setImportLoading] = useState(false);
  const [importWarning, setImportWarning] = useState<string | null>(null);

  const { currentPlan, setPlan, updatePlan } = useItinerary();
  const { changedActivityIds, removedActivityIds, addedActivityIds, applyReplan, clearDisruption } = useDisruption();
  const { loading: geminiLoading, callWithFallback } = useGemini();

  const handleReplan = useCallback((result: ReplanResult) => {
    updatePlan(result);
    applyReplan(result);
  }, [updatePlan, applyReplan]);

  const { messages, loading: chatLoading, sendMessage } = useChat(currentPlan, handleReplan);

  const handleTripSubmit = useCallback(async (formData: TripFormData) => {
    const sanitizedData: TripFormData = {
      ...formData,
      destination: sanitizeInput(formData.destination),
      interests: formData.interests.map((i) => sanitizeInput(i)),
      constraints: formData.constraints.map((c) => sanitizeInput(c)),
    };

    const prompt = buildPlanPrompt(sanitizedData);
    const { result, usedFallback, errorMsg } = await callWithFallback<TripPlan>(prompt, FALLBACK_TRIP);

    for (const day of result.days) {
      for (const activity of day.activities) {
        if (!activity.mapsUrl) {
          activity.mapsUrl = buildMapsSearchUrl(activity.location, result.destination);
        }
      }
    }

    setPlan(result);
    clearDisruption();
    setShowFallbackBanner(usedFallback);
    if (usedFallback && errorMsg) {
      setImportWarning(`API Error: ${errorMsg}`);
    } else {
      setImportWarning(null);
    }
    setMode('replanner');
  }, [callWithFallback, setPlan, clearDisruption]);

  const handleImport = useCallback(async (rawText: string) => {
    setImportLoading(true);
    setImportWarning(null);
    const { plan, warning } = await parseImportedTrip(rawText);
    setPlan(plan);
    clearDisruption();
    setImportWarning(warning ?? null);
    setImportLoading(false);
    setShowFallbackBanner(!!warning);
  }, [setPlan, clearDisruption]);

  /** Download the current plan as a .txt file */
  const handleDownload = useCallback(() => {
    if (!currentPlan) return;
    const text = generatePlanText(currentPlan);
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `wayshift-${currentPlan.destination.toLowerCase().replace(/\s+/g, '-')}-plan.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [currentPlan]);

  return (
    <div className="w-full min-h-screen bg-[#f8f9fa] text-gray-900">
      <Header mode={mode} onModeChange={setMode} hasPlan={!!currentPlan} />

      {/* Fallback banner */}
      {showFallbackBanner && (
        <div className="px-4 py-2">
          <div className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-[#FEF7E0] border border-[#FBBC04]/40 text-[#B06000] text-xs font-medium animate-fade-in">
            ⚠️ {importWarning || 'Using demo data — add VITE_GEMINI_API_KEY to .env.local for live generation'}
          </div>
        </div>
      )}

      {/* Main content */}
      <main className="w-full">
        {/* Planner panel — wider, less side space */}
        {mode === 'planner' && (
          <div
            role="tabpanel"
            id="panel-planner"
            aria-labelledby="tab-planner"
            className="w-full max-w-4xl mx-auto px-4 py-6"
          >
            <div className="bg-white border border-gray-200 rounded-2xl p-6 sm:p-8 shadow-sm">
              <div className="mb-6">
                <h2 className="text-lg font-bold text-gray-900 mb-1">
                  ✈️ Plan Your Trip
                </h2>
                <p className="text-sm text-gray-500">
                  Tell us about your dream trip and we&apos;ll create a detailed itinerary.
                </p>
              </div>
              <TripForm onSubmit={handleTripSubmit} loading={geminiLoading} />
            </div>
          </div>
        )}

        {/* Replanner panel */}
        {mode === 'replanner' && (
          <div
            role="tabpanel"
            id="panel-replanner"
            aria-labelledby="tab-replanner"
          >
            {!currentPlan ? (
              <div className="w-full max-w-4xl mx-auto px-4 py-6 space-y-6">
                <div className="bg-white border border-gray-200 rounded-2xl p-8 text-center shadow-sm animate-fade-in">
                  <div className="text-5xl mb-4">🗺️</div>
                  <h2 className="text-lg font-bold text-gray-900 mb-2">No trip loaded yet</h2>
                  <p className="text-sm text-gray-500 mb-4">
                    Create a trip in the Planner tab, or import an existing one below.
                  </p>
                  <button
                    type="button"
                    onClick={() => setMode('planner')}
                    className="bg-[#4285F4] hover:bg-[#3367D6] text-white px-6 py-2.5 rounded-xl font-medium text-sm transition-colors shadow-lg"
                  >
                    ✈️ Plan a Trip
                  </button>
                </div>
                <ImportTrip onImport={handleImport} loading={importLoading} />
              </div>
            ) : (
              /* Two-column: Chat + Itinerary — full width */
              <div className="w-full grid grid-cols-1 lg:grid-cols-2">
                {/* Left: Chat */}
                <div className="h-screen overflow-y-auto border-r border-gray-200 flex flex-col">
                  <div className="flex-1">
                    <ChatInterface
                      messages={messages}
                      loading={chatLoading}
                      onSendMessage={sendMessage}
                    />
                  </div>
                  <ImportTrip onImport={handleImport} loading={importLoading} />
                </div>

                {/* Right: Itinerary */}
                <div className="h-screen overflow-y-auto">
                  <ItineraryView
                    plan={currentPlan}
                    changedActivityIds={changedActivityIds}
                    removedActivityIds={removedActivityIds}
                    addedActivityIds={addedActivityIds}
                    onDownload={handleDownload}
                  />
                </div>
              </div>
            )}
          </div>
        )}
      </main>
    </div>
  );
}
